Repository AzzyIsNotHere/AzzyStation, pull requests merged in 2022-01, with the labels that each got.

#1 Darkens flash effect by default
  code/modules/client/preferences/darkened_flash.dm
Labels: Accessibility

#4 Removes "Gas-The-Lizards" Ruin
  config/spaceruinblacklist.txt
Labels: Requested

#5 Remove "GAS THE LIZARDS" ion law
  strings/ion_laws.json
Labels: Good First PR
